name: Generate API changes

on:
  workflow_dispatch:
    inputs:
      tag1:
        description: 'First ESMF Tag'
        required: true
        default: 'v8.3.0'
      tag2:
        description: 'Second ESMF Tag'
        required: true
        default: 'develop'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Dockerfiles
      uses: actions/checkout@v3
      with:
          repository: esmf-org/esmf-containers
          path: esmf-containers
          ref: main
    
    - name: Build Docker image  
      run: | 
        cd ${{ github.workspace }}/esmf-containers/api-change
        docker build . --tag esmf/api-change --build-arg TAG1="${{ inputs.tag1 }}" --build-arg TAG2="${{ inputs.tag2 }}"
        
    - name: Copy artifacts
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        CID=$(docker run -dit --name runner esmf/api-change)
        docker cp ${CID}:/artifacts/api_change-artifacts.zip ${{ github.workspace }}/artifacts
        docker stop ${CID}
        docker rm ${CID}
            
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: api-change
        path: ${{ github.workspace }}/artifacts
